[tool.poetry]
name = "msoffcrypto-tool"
version = "4.11.0"
description = "A Python tool and library for decrypting MS Office files with passwords or other keys"
license = "MIT"
homepage = "https://github.com/nolze/msoffcrypto-tool"
authors = ["nolze <nolze@archlinux.us>"]
readme = "README.md"
packages = [{ include = "msoffcrypto" }]

[tool.poetry.dependencies]
python = ">=2.7,<2.8 || >=3.6,<4"
cryptography = ">=2.3"
olefile = ">=0.45"

[tool.poetry.dev-dependencies]
nose = ">=1.3.7"
coverage = ">=4.5.1"
pytest = "^4.6.11"

[tool.poetry.scripts]
msoffcrypto-tool = 'msoffcrypto.__main__:main'

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
